### ISSUE TITLE
How to find PATH_TO_OVMF_CODE

### ISSUE THREAD

**Issue by FutureYu** [ultimaweapon/tcg-boot#2]
I don't know how to find `PATH_TO_OVMF_CODE`, I find `/usr/share/OVMF/OVMF_CODE.fd`，and run like `TCGBOOT_OVMF_CODE=/usr/share/OVMF/OVMF_CODE.fd ./vm/start.sh -cdrom ~/Desktop/ubuntu-20.04.2.0-desktop-amd64.iso 
`. But qemu just said
```
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
```
then sttuck.
I want to know how can I fix this, thanks!

**Comment by ultimaweapon** [comment]
From your logs it seems like your OVMF is correct. I guess Ubuntu installer required a display to output. So remove this line https://github.com/ultimaweapon/tcg-boot/blob/master/vm/start.sh#L14 and try again.

**Comment by FutureYu** [comment]
Wow! It works. Thanks a lot!!
