### ISSUE TITLE
Failed to startup

### ISSUE THREAD

**Issue by FutureYu** [ultimaweapon/tcg-boot#3]
![image](https://user-images.githubusercontent.com/32595791/115945879-516aeb80-a4f0-11eb-8a64-0c440e616c6b.png)
I tried to start the vm, but it said that something was not found. I want to know how can I fix this, thanks!

**Comment by ultimaweapon** [comment]
You need to update the configuration file that was copied from this file https://github.com/ultimaweapon/tcg-boot/blob/master/src/tcg-loader/default.conf to match with your system.
